### PR TITLE
Ticke ty4/adding monitor

### PR DESCRIPTION
**Pull request by lileddie**

### CODE REVIEW

**Comment by lileddie** [comment]
Ran Plan in dir: `.` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
exit status 1: running "sh -c terraform plan -input=false -refresh -no-color -out \"/root/.atlantis/repos/lileddie/testF5/7/default/default.tfplan\" -var atlantis_user=\"lileddie\" -var atlantis_repo=\"lileddie/testF5\" -var atlantis_repo_name=\"testF5\" -var atlantis_repo_owner=\"lileddie\" -var atlantis_pull_num=7" in "/root/.atlantis/repos/lileddie/testF5/7/default"
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

Error: Error running plan: 1 error(s) occurred:

* provider.bigip: BigIP provider requires address, username and password



```
</details>

**Comment by lileddie** [comment]
Ran Plan in dir: `.` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
exit status 1: running "sh -c terraform plan -input=false -refresh -no-color -out \"/root/.atlantis/repos/lileddie/testF5/7/default/default.tfplan\" -var atlantis_user=\"lileddie\" -var atlantis_repo=\"lileddie/testF5\" -var atlantis_repo_name=\"testF5\" -var atlantis_repo_owner=\"lileddie\" -var atlantis_pull_num=7" in "/root/.atlantis/repos/lileddie/testF5/7/default"
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

Error: Error running plan: 1 error(s) occurred:

* provider.bigip: HTTP 401 :: <?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>Authentication required!</title>
<link rev="made" href="mailto:support@f5.com" />
<style type="text/css"><!--/*--><![CDATA[/*><!--*/ 
    body { color: #000000; background-color: #FFFFFF; }
    a:link { color: #0000CC; }
    p, address {margin-left: 3em;}
    span {font-size: smaller;}
/*]]>*/--></style>
<style type="text/css"><!--/*--><![CDATA[/*><!--*/ 
* { width: 400px; font-size: 100%; font-style: normal; }
html { text-align: center; }
body { background: #ffffff; text-align: left; font-family: sans-serif; font-size: 70%; color: #333333; }

a,span { width: auto; } 
h1,h2,h3 { margin: 20px 0px 20px 0px; font-weight: bold; }

h1 { padding: 5px; border: 1px solid #999999; background: #eeeeee; color: #000000; font-size: 125%;  }
hr { height: 1px; border: none; border-top: 1px solid #999999; }
img { border: 0px; }
p { width: 350px; margin: 15px 25px 15px 25px; line-height: 135%; }
/*]]>*/--></style>

</head>

<body>
<h1>Authentication required!</h1>
<p>


    This server could not verify that you are authorized to access
    the URL "/mgmt/tm/net/self".
    You either supplied the wrong credentials (e.g., bad password), or your
    browser doesn't understand how to supply the credentials required.

  </p>
<p>


    In case you are allowed to request the document, please
    check your user-id and password and try again.

</p>

<h2>Error 401</h2>
<address>
  <a href="/">192.168.2.5</a><br />
  
  <span>Sun Nov 11 16:30:56 2018<br />
  </span>
</address>
</body>
</html>





```
</details>

**Comment by lileddie** [comment]
Ran Plan in dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

+ bigip_ltm_monitor.monitor80
      id:            <computed>
      destination:   "*:80"
      interval:      "15"
      ip_dscp:       "0"
      manual_resume: "disabled"
      name:          "/Common/http_monitor_80"
      parent:        "/Common/http"
      reverse:       "disabled"
      send:          "GET /status.html\\r\\n"
      time_until_up: "0"
      timeout:       "46"
      transparent:   "disabled"
Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://a61a5821.ngrok.io/lock?id=lileddie%252FtestF5%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by lileddie** [comment]
atlantis apply -d

**Comment by lileddie** [comment]
```
Error: flag needs an argument: 'd' in -d.
Usage of apply:
  -d, --dir string         Apply the plan for this directory, relative to root of
                           repo, ex. 'child/dir'.
  -p, --project string     Apply the plan for this project. Refers to the name of
                           the project configured in atlantis.yaml. Cannot be used
                           at same time as workspace or dir flags.
      --verbose            Append Atlantis log to comment.
  -w, --workspace string   Apply the plan for this Terraform workspace.
```

**Comment by lileddie** [comment]
atlantis apply

**Comment by lileddie** [comment]
Ran Apply in dir: `.` workspace: `default`

**Apply Failed**: Pull request must be approved before running apply.

**Comment by lileddie** [comment]
approved

**Comment by lileddie** [comment]
atlantis apply

**Comment by lileddie** [comment]
Ran Apply in dir: `.` workspace: `default`

**Apply Failed**: Pull request must be approved before running apply.

**Comment by lileddie-terraform** [comment]
terraform plan

**Comment by lileddie** [comment]
Did you mean to use `atlantis` instead of `terraform`?

**Comment by lileddie** [comment]
atlantis apply

**Comment by lileddie** [comment]
Ran Apply in dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
bigip_ltm_monitor.monitor80: Creating...
  destination:   "" => "*:80"
  interval:      "" => "15"
  ip_dscp:       "" => "0"
  manual_resume: "" => "disabled"
  name:          "" => "/Common/http_monitor_80"
  parent:        "" => "/Common/http"
  reverse:       "" => "disabled"
  send:          "" => "GET /status.html\\r\\n"
  time_until_up: "" => "0"
  timeout:       "" => "46"
  transparent:   "" => "disabled"
bigip_ltm_monitor.monitor80: Creation complete after 1s (ID: /Common/http_monitor_80)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```
</details>

**Comment by lileddie** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
